# Generated by Django 2.2.4 on 2019-09-13 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('home', models.BooleanField(default=False)),
                ('maincategory', models.BooleanField(default=False)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='homeStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('home', models.BooleanField(default=False)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ml_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('extras', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('slideUrl', models.URLField(blank=True, null=True)),
                ('inputs_csv', models.FileField(upload_to='inputs/')),
                ('result_key', models.CharField(blank=True, max_length=50, null=True)),
                ('showSlide', models.BooleanField(default=False)),
                ('input_ppt', models.FileField(default=False, upload_to='slide/')),
                ('locations', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(default=0, related_name='category', to='virtusa.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='homeCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeCategory', to='virtusa.homeStack'),
        ),
    ]
