# Generated by Django 2.2.2 on 2019-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ml_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('extras', models.TextField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('inputs_csv', models.FileField(upload_to='static/inputs/')),
            ],
        ),
    ]
