# Generated by Django 2.2.2 on 2019-08-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0002_ml_models_result_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ml_models',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='virtusa.category'),
        ),
    ]
