# Generated by Django 2.2.2 on 2019-08-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0003_auto_20190813_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_models',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtusa.category'),
        ),
    ]
