# Generated by Django 2.2.2 on 2019-08-13 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0005_auto_20190813_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ml_models',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
