# Generated by Django 2.2.2 on 2019-08-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0006_auto_20190813_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml_models',
            name='category',
        ),
        migrations.AddField(
            model_name='ml_models',
            name='category',
            field=models.ManyToManyField(default=0, to='virtusa.category'),
        ),
    ]
