# Generated by Django 2.2.2 on 2019-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0007_auto_20190813_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_models',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
