# Generated by Django 2.2.2 on 2019-08-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0008_ml_models_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_models',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
