# Generated by Django 2.2.4 on 2019-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0009_auto_20190813_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
