# Generated by Django 2.2.4 on 2019-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0010_category_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ml_models',
            name='locations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
