# Generated by Django 2.2.4 on 2019-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0012_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_models',
            name='inputs_csv',
            field=models.FileField(upload_to='inputs/'),
        ),
    ]
