# Generated by Django 2.2.4 on 2019-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0013_auto_20190816_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_models',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
