# Generated by Django 2.2.4 on 2019-08-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa', '0014_ml_models_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_models',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
